project_id = "jrtjupqvxvhbjjhuasrw"

[functions.ai-coach]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.photo-derivatives]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.email-hook]
verify_jwt = false

[functions.send-password-reset]
verify_jwt = false

[functions.save-onboarding]
verify_jwt = false

[functions.validate-email-domain]
verify_jwt = false

[functions.summarize-resource]
verify_jwt = false
